config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  get 'commitments/index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :hackdays do
    resources :projects
    resources :pitches, only: [:index, :create, :destroy]
  end

  resources :projects do
    resources :goals
  end

  resources :goals do
    resource :commitment, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show]

  root to: 'hackdays#index'
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :hackday, inverse_of: :goals
  belongs_to :project, inverse_of: :goals
  has_many :commitments, inverse_of: :goal, dependent: :destroy
  has_many :users, through: :commitments
  has_many :likes, dependent: :destroy

  validates :aim, presence: true
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  helper_method :hackday, :commitments

  def index
    @goals = hackday.goals.order(created_at: :desc)
    @project_form = ProjectForm.new(Project.new, hackday)
  end

  def create
    @project_form = ProjectForm.new(project, hackday, params)
    @project_form.goal.aim ||= @project_form.project.name
    if @project_form.save
      render partial: "goals/goal", object: @project_form.goal
    else
      logger.info @project_form.errors.full_messages.inspect
      head :not_acceptable
    end
  end

  private

  def hackday
    @hackday ||= HackdayFromDate.from_param(params[:hackday_id]).hackday
  end

  def project
    @project = if params[:project][:id].present?
      Project.find(params[:project][:id])
    else
      Project.new
    end
  end
end

app/views/pitches/index.html.haml
%header
  .inner
    %h1 Hackdays pitches
    %h2= dates(hackday)

%section.new-pitch
  .inner
    = form_for @project_form, url: hackday_pitches_path(hackday), method: :post, html: { class: "pitching-form" } do |form|
      .fields
        .field
          = form.label :user_ids, "Team"
          = form.select :user_ids, user_ids_for_select, {}, { multiple: true, "data-placeholder": "Team members" }
        .field
          = form.label :name do
            %span Project
            = form.select :id, [[nil, nil]] + project_ids_for_select, {}, { "data-placeholder": "Select existing project", tabindex: -1 }
          = form.text_field :name
        = form.fields_for :goal do |fields|
          .field
            = fields.label :aim, "Goal"
            = fields.text_field :aim

      = form.submit "Add pitch"

%section.other-projects
  .inner
    %h2 Pitches

    %ul.goals
      = render @goals