config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  get 'commitments/index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :hackdays do
    resources :projects
    resources :pitches, only: [:index, :create, :destroy]
  end

  resources :projects do
    resources :goals
  end

  resources :goals do
    resource :commitment, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show]

  root to: 'hackdays#index'
end

app/models/hackday.rb
class Hackday < ApplicationRecord
  has_many :goals
  has_many :projects, through: :goals
  has_many :commitments, through: :goals

  before_validation :fill_in_dates

  validates :start_date, :end_date, presence: true
  validate :dates_in_order, :if => [:start_date?, :end_date?]

  def name
    start_date.strftime("Hackdays %B %Y")
  end

  def to_param
    start_date.strftime("%Y-%m")
  end

  def current?
    start_date <= Date.today && Date.today <= end_date
  end

  def past?
    end_date < Date.today
  end

  def future?
    start_date > Date.today
  end

  def <=>(another)
    start_date <=> another.start_date
  end

  def self.current
    where("start_date <= :today AND end_date >= :today", today: Date.today)
      .first
  end

  def self.next
    where("start_date > ?", Date.today)
      .order(start_date: :asc)
      .first
  end

  def self.upcoming
    where("end_date >= ?", Date.today)
      .order(start_date: :asc)
  end

  def self.most_recent_first
    order(start_date: :desc)
  end

  def self.with_goals
    includes(:goals => [:project, { :commitments => :user }])
  end

  private

  def dates_in_order
    errors.add(:end_date, "must be after start date") \
      unless end_date >= start_date
  end

  def fill_in_dates
    self.start_date ||= Date.today
    self.end_date ||= start_date + 1.day
  end
end

app/controllers/hackdays_controller.rb
class HackdaysController < ApplicationController
  helper_method :hackday, :commitments

  def index
  end

  def show
    @commitments = CommitmentsForUser.new(current_user, hackday).commitments
    @goals = HackdayGoals.new(hackday).goals
  end

  private

  def hackday
    @hackday ||= HackdayFromDate.from_param(params[:id]).hackday
  end
end

app/helpers/hackdays_helper.rb
module HackdaysHelper
  def effort(hackday)
    users = hackday.goals.flat_map(&:users).uniq
    [
      users.size,
      "person".pluralize(users.size),
      hackday.past? ? "worked on" : "working on",
      hackday.goals.size,
      "goal".pluralize(hackday.goals.size)
    ].join(" ")
  end
end

app/views/hackdays/_current.html.haml
- if hackday.present?
  %header.current-hackdays
    .inner
      .info
        %h1= hackday.name
        .dates= dates(hackday)
      = link_to hackday do
        %i.material-icons chevron_right

app/views/hackdays/_next.html.haml
- if hackday.present?
  %section.next-hackdays
    .inner
      %h2 Next Hackdays
      .dates= link_to dates(hackday), hackday

app/views/hackdays/index.html.haml
= render "current", hackday: Hackday.current

%section.what-is-hackdays
  .inner
    %p
      Powershop Hackdays
      is a chance to work on projects outside of what we do every day,
      in order to learn new skills, embrace new ideas and new ways of working,
      and form new relationships with fellow developers.
    %p
      Pitch your ideas on Thursday morning, form teams, and spend two days
      working on your projects. Then we come together on Friday afternoon
      to present our progress, share what we've learned, and find out
      who will take home the coveted Golden Sausage Roll.

= render "next", hackday: Hackday.next

app/views/hackdays/show.html.haml
%header
  .inner
    %h1= hackday.name
    .dates= dates(hackday)
    .effort= effort(hackday)

- if @commitments.any?
  %section.commitments
    .inner
      %h3= tense(hackday, ".working")
      %ul.goals
        = render @commitments.map(&:goal)
      = link_to "Add a project", new_hackday_project_path(hackday), class: "button"
- elsif !hackday.past?
  %section.no-project
    .inner
      %h2= t(".no_commitment")
      %p= t(".browse_or_add")
      = link_to "Add a project", new_hackday_project_path(hackday), class: "button"

- if other_goals.any?
  %section.other-projects
    .inner
      %h2= tense(hackday, ".goals")

      %ul.goals
        = render other_goals