config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  get 'commitments/index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :hackdays do
    resources :projects
    resources :pitches, only: [:index, :create, :destroy]
  end

  resources :projects do
    resources :goals
  end

  resources :goals do
    resource :commitment, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show]

  root to: 'hackdays#index'
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_url :name,
    only_when_blank: true,
    limit: 64

  has_many :goals, inverse_of: :project, autosave: true, dependent: :destroy

  validates :name, presence: true
  validates :url, format: { with: /\A[a-z0-9\-]+\z/ }, if: :name?

  def to_s
    name
  end

  def to_param
    url
  end

  def contributors
    goals.flat_map(&:users).uniq
  end

  def most_recent_hackday
    goals.sort_by(&:hackday).last.try(:hackday)
  end

  def self.with_full_information
    includes(:goals => [:hackday, { :commitments => :user }])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :hackday

  def index
    @hackdays = Hackday.most_recent_first.with_goals
  end

  def show
    project
  end

  def new
    @project_form = ProjectForm.new(Project.new, hackday)
  end

  def create
    @project_form = ProjectForm.new(Project.new, hackday, params)

    if @project_form.save
      @project_form.goal.commitments.create(user: current_user) if hackday
      redirect_to @project_form.project
    else
      render :new
    end
  end

  def edit
    @project_form = ProjectForm.new(project, nil)
  end

  def update
    @project_form = ProjectForm.new(project, nil, params)

    if @project_form.save
      redirect_to @project_form.project
    else
      render :edit
    end
  end

  private

  def hackday
    @hackday = params[:hackday_id] &&
      HackdayFromDate.from_param(params[:hackday_id]).hackday
  end

  def project
    @project ||= Project.with_full_information.find_by(url: params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def new_project_form_path
    if hackday.present?
      hackday_projects_path(hackday)
    else
      projects_path
    end
  end

  def working_on?(goal)
    goal.users.include?(current_user)
  end

  def other_goals
    @goals.reject { |goal| working_on?(goal) }
  end

  def project_goals
    @project.goals.sort { |g1, g2| g2.hackday <=> g1.hackday }
  end

  def project_ids_for_select
    Project.order(name: :asc).pluck(:name, :id)
  end
end

app/views/projects/_form.html.haml
%section
  .inner
    .field
      = form.label :name
      = form.text_field :name
      = form.error_messages_for :name
    %p.field-hint Something memorable!

    .field
      = form.label :description
      = form.text_area :description, rows: 10
      = form.error_messages_for :description
    %p.field-hint What's exciting about this project? What technologies will you use? What will you deliver?

    .field
      = form.label :repository_url
      = form.url_field :repository_url, rows: 10
      = form.error_messages_for :repository_url
    %p.field-hint Let others browse your code.

app/views/projects/_goal.html.haml
%section.goal
  .inner
    %h4= dates(goal.hackday, true)
    .committed-users= users(goal.users.to_a)
    = markdown goal.aim

    - unless goal.hackday.past?
      = link_to "Edit", edit_goal_path(goal), class: "button"

app/views/projects/_hackday.html.haml
- if hackday.projects.any?
  %section.project-list
    .inner
      %h3= link_to dates(hackday), hackday
      = render hackday.projects

app/views/projects/_project.html.haml
%article.project
  %h4= link_to project.name, project
  .users= users(project.contributors)

app/views/projects/edit.html.haml
%header
  .inner
    %h1 Edit project details

= form_for @project_form, url: project_path(@project_form.project) do |form|
  = render partial: "form", object: form

  %section.buttons
    .inner
      = form.submit "Save changes"

app/views/projects/index.html.haml
%header
  .inner
    %h1 All projects

= render partial: "hackday", collection: @hackdays

app/views/projects/new.html.haml
%header
  .inner
    %h1 New Hackdays project

= form_for @project_form, url: new_project_form_path do |form|
  = render partial: "form", object: form

  - if hackday.present?
    %section
      .inner
        %h2 2-day goal

        %div
          = form.fields_for :goal, Goal.new do |fields|
            .field
              = fields.label :aim
              = fields.text_area :aim, rows: 3
              = form.error_messages_for :"goals.aim"
            %p.field-hint What do you aim to deliver during this Hackdays?

            .field
              = fields.label :help_required
              = fields.text_area :help_required, rows: 3
              = form.error_messages_for :"goals.help_required"
            %p.field-hint Are you looking for any help? Make your pitch here!

  %section.buttons
    .inner
      = form.submit "Create project"

app/views/projects/show.html.haml
%header
  .inner
    %h1= @project.name

%section.project-info
  .inner
    .description
      %h3 Project description
      - if @project.description.present?
        = markdown @project.description
      - else
        %p No description yet. If this is your project, why not brag about it a bit?
      %p
        = link_to "Edit this project", edit_project_path(@project), class: "button"
        = link_to "Add a goal", new_project_goal_path(@project), class: "button"
    .contributors
      %h3 Contributors
      %ul
        = render @project.contributors
      - if @project.repository_url
        %h3 Source code
        %p= link_to "View source code", @project.repository_url, target: :_blank

= render partial: "goal", collection: project_goals