config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  get 'commitments/index'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  resources :hackdays do
    resources :projects
    resources :pitches, only: [:index, :create, :destroy]
  end

  resources :projects do
    resources :goals
  end

  resources :goals do
    resource :commitment, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show]

  root to: 'hackdays#index'
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :hackday, inverse_of: :goals
  belongs_to :project, inverse_of: :goals
  has_many :commitments, inverse_of: :goal, dependent: :destroy
  has_many :users, through: :commitments
  has_many :likes, dependent: :destroy

  validates :aim, presence: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  helper_method :project

  def new
    @goal = project.goals.build
  end

  def create
    @goal = project.goals.build(goal_params)
    @goal.hackday = Hackday.upcoming.first
    if @goal.save
      redirect_to project
    else
      render :new
    end
  end

  def edit
    goal
  end

  def update
    if goal.update(goal_params)
      redirect_to goal.project
    else
      render :edit
    end
  end

  private

  def project
    @project ||= Project.find_by(url: params[:project_id])
  end

  def goal_params
    params.require(:goal).permit(:aim, :help_required)
  end

  def goal
    @goal ||= Goal.includes(:project).find(params[:id])
  end
end

app/views/goals/_form.html.haml
%section
  .inner
    .field
      = form.label :aim
      = form.text_area :aim, rows: 3
      = form.error_messages_for :aim
    %p.field-hint What do you aim to deliver during this Hackdays?

    .field
      = form.label :help_required
      = form.text_area :help_required, rows: 3
      = form.error_messages_for :help_required
    %p.field-hint Are you looking for any help? Make your pitch here!

app/views/goals/_goal.html.haml
%li.goal
  %h4
    = link_to goal.project.name, goal.project
  .committed-users
    - unless goal.hackday.past?
      - if working_on?(goal)
        = link_to "Actually, nah", goal_commitment_path(goal), method: :delete, class: "button"
      - else
        = link_to "Sign me up!", goal_commitment_path(goal), method: :post, class: "button"
    = users(goal.users.to_a)

  = markdown goal.aim
  - if goal.help_required? && !working_on?(goal)
    %p.help
      %b Help required:
      = goal.help_required

  = render "goals/likes", goal: goal

app/views/goals/_likes.html.haml
.likes{"data-liked": liked?(goal), "data-url": goal_like_path(goal)}
  %i.material-icons favorite_border
  %span
    - if goal.likes_count.zero?
      Be the first to like this
    - else
      = goal.likes_count
      = "person".pluralize(goal.likes_count)
      = goal.likes_count > 1 ? "like" : "likes"
      = "this"

app/views/goals/edit.html.haml
%header
  .inner
    %h1 Edit goal
    %h2= "#{@goal.project.name}, #{dates(@goal.hackday)}"

= form_for @goal do |form|
  = render partial: "form", object: form

  %section.buttons
    .inner
      = form.submit "Save changes"

app/views/goals/new.html.haml
%header
  .inner
    %h1 New goal
    %h2= "#{project.name}, #{dates(Hackday.upcoming.first)}"

= form_for @goal, url: project_goals_path(project) do |form|
  = render partial: "form", object: form

  %section.buttons
    .inner
      = form.submit "Add goal"